- board_filling_game/board_filling_game.py
Added a board filling game with the following rules:
1. Enter coordinates to put the pieces on the board.
2. Enter (0, 0) to pass the turn.
3. Try to fill the board with as few turns as possible
> Board filling game

- rock_paper_scissors/rock_paper_scissors.py
Made really small changes about:
- points:  1 wins, -1 loses and 0 ties
- changed the sequence in the dictionary
i want to add the feature of cleaning the screen after the first game in the console, would you be happy about it?
> Small changes for readability

- tic_tac_toe/README.md
- tic_tac_toe/tic_tac_toe.py
Adding a Tic Tac Toe game in python
> Tic Tac Toe Game

- README.md
Hello, this PR just fixes a very minor typo in the README.md
> fixed minor typo in readme

- black_jack/main.py
And there is the classic casino's shuffle at 60ish cards
Everything is tested
> [BUG FIX #7 ]  Now cards are limited

- snake_game/README.md
- snake_game/game.py
Description
This pull request adds a pause/unpause feature to the Snake game. When the 'p' key is pressed, the game toggles between pause and unpause states. This feature gives players the option to take a break and resume play without resetting the game.
Changes
Added 'toggle_pause' function in the main game file (game.py) which pauses and unpauses the game.
Integrated the 'toggle_pause' function with key event listening, bound to 'p' key press.
Testing
I tested the changes by playing the game. The game paused when the 'p' key was pressed, stopping the movement of the snake. Pressing 'p' again unpaused the game, and the snake resumed movement from its last direction.
Concerns
None at this time. This pause/unpause feature appears to be working as intended without any noticeable issues. …
> Add pause/unpause functionality to snake game

- tic_tac_toe/tic_tac_toe.py
display_board printed dynamically. all() function for checking win conditions along with generator expression. Boundary check for players move added.
> Updated Code

- README.md
Hi. I made a few improvements to the [README](https://github.com/AseanK/python-tools-and-games/blob/main/README.md):
- Improved conciseness issues
- Improved consistency issues regarding uppercase letters
- Resized the "fork" image to keep its original ratio
- Added alternative command options for cloning the repo
Hope this helps!
> Added minor improvements to the README.

- Games/treasure_Island/README.md
- Games/treasure_Island/main.py
> Add Treasure Island

- Games/checkers/README.md
- Games/checkers/checkers.py
I have created a simple tkinter checkers game.
> add checkers

- Tools/AutoWiFiCheck/README.md
- Tools/AutoWiFiCheck/wifi_checker.py
Added python script (wifi_checker.py) and readme file under TOOLS folder.
> Add WiFi Checker Tool

- Games/checkers/checkers.py
Hello! Beginner to coding and attempting to input a recursive function to allow user for double jump move. Any suggestions
My input between lines 127-129
Thanks
> Recursive double move try. Suggestion encouraged!

- Games/gambler/gambler.py
- Corrected the spelling for variable "answer"
- Inserted input check for cup entry if value less than 1 or greater than 3 
- swapped "$" before entry for readability
> Spell check answer. Input validation for cup entry

- Tools/merge_pdf/README.md
- Tools/merge_pdf/merge_pdf.py
Added python script (merge_pdf.py) and readme file under TOOLS folder.
> Add Merge PDFs' tool

- Tools/text_summarizer/README.md
- Tools/text_summarizer/main.py
> add simple text summarizer

- Tools/Image_resizer/image_resize.py
I often need to resize Image because of file size limit.
Before, i use internet Image_resizer. But I don't know how they use my image.
So I make image resizer.
It can resize extension png, jpg. I use Pillow library. So It can awfully decrease Image size.
I want to you confirm and accept this pull request. Thank you.
> Add Image_Resizer tool

- Tools/remove_duplicates/README.md
- Tools/remove_duplicates/main.py
I chose this repository for my first open-source contribution. Thank you for creating a repository that makes it easy to contribute. This is a simple tool that removes duplicate lines from a text file. Thank you!
> add remove_duplicates tool

- Tools/Password_strength_checker/main.py
* Implement password strength checker with GUI support
I implement a "password strength checker" tool that can be utilized across various projects to contribute to this repository. 
In projects, setting a secure password is a critical part of user authentication, as it provides the first line of defense against unauthorized access. 
A password strength checker, like this one, evaluates the complexity and resilience of passwords, ensuring they meet essential security standards such as length, use of diverse character types, and avoidance of dictionary words. 
This feature includes a GUI, allowing users to easily verify its functionality. 
Implementing this feature helps prevent common security breaches due to weak passwords, enhancing overall user data protection.
Issue : #52
> Add Password Strength Checker Tool

- Tools/bluetooth_scanner/README.md
- Tools/bluetooth_scanner/bluetooth_scanner.py
This pull request introduces a new feature that enables scanning for nearby Bluetooth devices within the application. It utilizes PyQt5's QtBluetooth module to discover and list both available and connected Bluetooth devices. This enhancement allows users to manage Bluetooth peripherals directly from the application, improving the overall user experience.
- **Added** `bluetooth_scanner.py` containing the `BluetoothScanner` class.
- Initializes a Bluetooth device discovery agent.
- Connects signals to handle device discovery and scan completion.
- Filters out devices without names or with default naming patterns.
- Lists discovered and connected devices upon scan completion.
- **Modified** project requirements to include PyQt5 with Bluetooth support.
The application previously lacked …
> Add Bluetooth device detection tool 

- Tools/custom_password_generator/custom_password_generator.py
> custom_password_generator with no extra files.

- Tools/remove_duplicates/README.md
- Tools/remove_duplicates/main.py
- Tools/remove_duplicates/main_gui.py
1. GUI Addition
2. Support for Additional File Formats:
- Added functionality to handle .txt, .csv, .json, .xlsx, and .xml file formats
> Enhance Functionality: Add GUI and Support for Multiple File Formats

- Tools/custom_password_generator/custom_password_generator.py
- Added type hints to functions and variables using the `typing` module.
- Utilized `Optional` to explicitly handle cases where values can be `None`.
- Improved code readability and maintainability with clear type annotations.
- Ensured compatibility with static type checkers like `mypy`.
> Enhance `custom_password_generator.py` with Python Typing and Optional

- Tools/Image encoding and decoding/README.md
- Tools/Image encoding and decoding/image_encoding_and_decoding.py
Sharing images between systems or users often requires transferring large binary files, which can be inconvenient over text-based communication platforms such as email, chat, or forums. Users who want to embed or share images in text format face challenges without a seamless way to encode images into sharable text.
---
The program already supports converting images into Base64-encoded text, making it easier to share images in a purely text-based format. To further emphasize and improve this functionality:
1. Highlight the ability to encode images into text for sharing in the program's UI or documentation.
2. Include options to:
- Quickly copy the encoded text to the clipboard.
- Automatically split the encoded text into smaller chunks to fit platform-specific character limits (e.g., …
> [Feature] Add Image encoding/decoding tool 

- Tools/Image_resizer/image_resize.py
Add Webp Extension
Even if Animation Webp, It can reduce file size
When i test this code, File size reduce about 18%
> Add extension Webp at image_resize.py

- Games/memory_game/README.md
- Games/memory_game/memory-game.py
This pull request adds a new Memory Card Game to the Awesome Open Source Python Games and Tools repository. The game provides a fun and interactive way for beginners to practice Python programming skills.
- 4x4 grid memory matching game
- Emoji-based card symbols
- Move and pair tracking
- Command-line interface
- Simple and intuitive gameplay
- Dynamic board generation
- Card revealing and matching mechanics
- Input validation
- Clear screen for better user experience
- Performance tracking (moves and pairs found)
Addresses #2
> Feature: Add new game "Memory Game"

- Tools/NATO_alphabet_translator/README.md
- Tools/NATO_alphabet_translator/translator.py
1) Added single check statement that will check if letter is entered
2) Removed redundant while loop (outer) because there is no way to break out of program once you start it
3) Removed redundant quit statement in Intro() function
4) Moved intro() inside single function as its all prints statements
> Code cleanup of Nato Alphabet tool.

- Games/magic8ball/README.md
- Games/magic8ball/magic8ball.py
Hey, this is a magic8ball game. More like a fortune teller. 
I hope you merge this into the Games folder. Thanks!
> magic8ball game added

- .github/workflows/update-readme.yml
- README.md
- Tried to enhance the overall appeal of this repo's README
- Added an auto-update feature for Games and Tools folder which detects new additions and updates the list
Hope this meets the requirements. Thanks!
> PS: The number of commits is high because I am new to the working of git. Hope you understand.
> Updated README.md
